# Source - https://stackoverflow.com/a
# Posted by Henry Schreiner, modified by community. See post 'Timeline' for change history
# Retrieved 2025-11-26, License - CC BY-SA 4.0

repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
      - id: clang-format
        files: \.(cpp|h)$
